name: Build latest image
on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Log into registry
      env:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      run: podman login ghcr.io -u ${username} -p ${password}

    - name: Build image
      run: podman build . -t ghcr.io/jbpratt/supertuxkart/server:latest

    - name: Push image to registry
      run: podman push ghcr.io/jbpratt/supertuxkart/server:latest
